spring:
  application:
    name: events
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5433/events
    username: postgres
    password: ""
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jersey:
    type: filter
    application-path: /

logging:
  level:
    liquibase: DEBUG
    org.springframework: INFO